### PR TITLE
Bugfix/controller flow menu

### PR DESCRIPTION
**Pull request by m4rtint**
Branched From incontrol PR

### CODE REVIEW

**Comment by m4rtint** [comment]
[Can still start the game without controller selection](https://trello.com/c/5m3K6oVJ/117-can-still-start-the-game-without-controller-selection)

**Comment by m4rtint** [comment]
[Menus still shows on background](https://trello.com/c/kLbiBC0z/137-menus-still-shows-on-background)

**Comment by m4rtint** [comment]
[Menus still shows on background](https://trello.com/c/kLbiBC0z/137-menus-still-shows-on-background)

**Comment by m4rtint** [comment]
[Allow controller to select menu components](https://trello.com/c/X6i0T5Uh/147-allow-controller-to-select-menu-components)

**Comment by mikeslgoh** [comment]
Is this ok to review and merge now that I just merged the full version of InControl?

**Pull request merged**
