### PR TITLE
Feature/new colour scheme

### PR DESCRIPTION
**Pull request by spicyroboto**

### CODE REVIEW

**Comment by Gursaanj** [comment]
[Indicate Who won (which player) at the end of the game](https://trello.com/c/tSiCI5Bd/143-indicate-who-won-which-player-at-the-end-of-the-game)

**Comment by Gursaanj** [comment]
[Update UI to match chosen colour scheme](https://trello.com/c/hCCowiHM/157-update-ui-to-match-chosen-colour-scheme)

**Comment by Gursaanj** [comment]
IMG_20190925_200017

The text looks a bit small? or are we okay with that?

**Comment by mikeslgoh** [comment]
> IMG_20190925_200017
> 
> The text looks a bit small? or are we okay with that?

yeah if possible let's try and figure that out before merging

**Pull request merged**
