### PR TITLE
Update to readme, removed images

### PR DESCRIPTION
**Pull request by m4rtint**

### CODE REVIEW

**Comment by Gursaanj** [comment]
[Change the header in all scripts from "Gotty" to "Angry Goose Games"](https://trello.com/c/nOoKph8o/185-change-the-header-in-all-scripts-from-gotty-to-angry-goose-games)

**Comment by mikeslgoh** [comment]
Do we need to merge this before the previous PR or does it no matter @m4rtint ?

**Comment by m4rtint** [comment]
Doesn't matter for this pr. It's independent

**Comment by Gursaanj** [comment]
[Removed Gif from Repo's ReadMe](https://trello.com/c/kQVgshkQ/190-removed-gif-from-repos-readme)

**Pull request merged**
