### PR TITLE
Replace incontrol with full version

### PR DESCRIPTION
**Pull request by m4rtint**
I just replaced the InControl folder.

Try to checkout and try it out. See if there are any warnings.

### CODE REVIEW

**Comment by DJSteins** [comment]
Why are there 927 files changed???

**Comment by mikeslgoh** [comment]
> Why are there 927 files changed???

Most likely because Martin just replaced and imported a whole package so there must have been a lot of files in it.

**Comment by m4rtint** [comment]
> Why are there 927 files changed???

Yes, i just replaced a folder.

**Comment by DJSteins** [comment]
Did you do anything else other than replace that folder? If so they should be two separate PRs.

**Comment by m4rtint** [comment]
> Did you do anything else other than replace that folder? If so they should be two separate PRs.

Nope, only replaced the folder

**Comment by m4rtint** [comment]
> Hopefully, this will help us detecting controllers better

Blame the controllers, not the game

**Comment by m4rtint** [comment]
[Integrate full InControl](https://trello.com/c/WW71ccnD/140-integrate-full-incontrol)

**Pull request merged**
